# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luca Bozzetto
email: luca.bozzetto@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Studente di Informatica presso Università Ca'Foscari di Venezia.
  Appassionato di Infosec e Web  Development.
  Pubblico sul mio blog articoli a tema IT e non solo.
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: /:categories/:title/
url: "https://lucabozzetto.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitterLink: "https://twitter.com/LucaBozz"
github:  "https://github.com/lucabozzetto"
userprofile_img: "https://pbs.twimg.com/profile_images/828608142854467584/hhne0pE3_400x400.jpg"
linkedin: "https://www.linkedin.com/in/lucabozzetto"
include: [.nojekyll]
t:
  en:
    about: "About"
    education: "Education"
    contactme: "Contact Me"
  it:
    about: "Chi Sono" 
    education: "Istruzione"
    contactme: "Contattami"

social:
  name: Luca Bozzetto
  links:
    - https://twitter.com/LucaBozz
    - "https://www.linkedin.com/in/lucabozzetto"
    - "https://github.com/lucabozzetto"

twitter:
  username: LucaBozz
  card: summary

#ALGOLIA 
algolia:
   files_to_exclude:
     - tag/*/*.html
     - /*.html
     - /assets/*.*
     - /blog/*.*
   application_id: 3RQ16GFO74
   index_name: jekyll
   search_only_api_key: 18216a575b20060d5d29081e155ffce2


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-email-protect
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-admin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
